export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/hOx2kPyniEHJj9wquzJMuStFFUG.jpg",
    genre_ids: [28, 80, 53],
    id: 770906,
    original_language: "te",
    original_title: "Salaar: Part 1 – Ceasefire",
    overview:
      "In the city of Khansaar, Raja Mannar plans to make his son, Vardharaja Mannar his successor, but Raja Mannar's ministers and advisors plan a coup d'état by hiring armies from Russia and Serbia to attack and kill Vardha and Raja. Vardha, along with his brother and a few trusted men, manage to escape from Khansaar. Vardha goes to his childhood best friend, Deva, who learns about his predicament and sets out to make him the undisputed successor of Khansaar.",
    popularity: 20.506,
    poster_path: "/47Qhmf5OySjG5QUcfVqzqzjpCS2.jpg",
    release_date: "2023-12-21",
    title: "Salaar: Part 1 – Ceasefire",
    video: false,
    vote_average: 6.9,
    vote_count: 23,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/yfc7xWwLlEacjoOH4TRgb3tAaAe.jpg",
    genre_ids: [28, 80, 53],
    id: 770906,
    original_language: "te",
    original_title: "సలార్: పార్ట్‌ 1 – సీజ్‌ఫైర్‌",
    overview:
      "Set in the fictional dystopian city-state of Khansaar, the film follows the friendship between Deva, a tribesman, and Varadha, the prince of Khansaar. When a coup d'état is planned by his father's ministers and his relatives, Varadha enlists Deva's help to become Khansaar's undisputed ruler.",
    popularity: 28.901,
    poster_path: "/47Qhmf5OySjG5QUcfVqzqzjpCS2.jpg",
    release_date: "2023-12-21",
    title: "Salaar: Part 1 - Ceasefire",
    video: false,
    vote_average: 6.582,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: "/yJ75x2trRV8JMI7T1n1t7OWc4sg.jpg",
    genre_ids: [28, 18],
    id: 811941,
    original_language: "te",
    original_title: "దేవర: Part 1",
    overview: "Weapons recite the story of one man and his terrifying tale.",
    popularity: 4.305,
    poster_path: "/8FBhil5ZwTT3PP0l15jyWicoxHQ.jpg",
    release_date: "2024-10-10",
    title: "Devara: Part 1",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xog6M87uhSR9RiqQHqmJodluZho.jpg",
    genre_ids: [28, 53],
    id: 1080365,
    original_language: "te",
    original_title: "They Call Him OG",
    overview:
      'OG revolves around a ruthless gangster named Ojas Gambheera "OG" who returns to Mumbai after disappearing for 10 years on a personal crusade to finish crime bosses.',
    popularity: 2.055,
    poster_path: "/uDg52hGwy4Dm8hGGVYK3PHQzsKc.jpg",
    release_date: "2024-09-27",
    title: "They Call Him OG",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/aEY2afhvzJT0yzxLsufJG0Kg9mO.jpg",
    genre_ids: [878, 28, 14],
    id: 801688,
    original_language: "te",
    original_title: "కల్కి 2898 - ఎ.డి",
    overview:
      "When the world is taken over by darkness, a new force will arise.",
    popularity: 4.91,
    poster_path: "/d1uUM4GTXpc5c2VjZNOUCOwpsDg.jpg",
    release_date: "2024-05-09",
    title: "Kalki 2898 - AD",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/gGSS8qW3r2dmNSIU0nrL4wh9Cgv.jpg",
    genre_ids: [27, 35, 10749],
    id: 1022453,
    original_language: "te",
    original_title: "ది రాజా సాబ్",
    overview: "A couple fights destiny and negative forces for their love.",
    popularity: 0.921,
    poster_path: "/ejsOncU1lxaK7iwL2HwjnLYKWKG.jpg",
    release_date: "2025-01-10",
    title: "The Raja Saab",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },

  {
    adult: false,
    backdrop_path: "/wRxLAw4l17LqiFcPLkobriPTZAw.jpg",
    genre_ids: [28, 53],
    id: 697843,
    original_language: "en",
    original_title: "Extraction 2",
    overview:
      "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
    popularity: 113.307,
    poster_path: "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
    release_date: "2023-06-09",
    title: "Extraction 2",
    video: false,
    vote_average: 7.471,
    vote_count: 2191,
  },
  {
    adult: false,
    backdrop_path: "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 246.56,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 7.743,
    vote_count: 5772,
  },
  {
    adult: false,
    backdrop_path: "/1GGc5XXaFgNBoJnOEBJCnXSMwhx.jpg",
    genre_ids: [28, 80, 53],
    id: 743563,
    original_language: "ta",
    original_title: "விக்ரம்",
    overview:
      "Amar is assigned to investigate a case of serial killings. When Amar investigates the case, he realizes it is not what it seems to be and following down this path will lead to nothing but war between everyone involved.",
    popularity: 9.947,
    poster_path: "/774UV1aCURb4s4JfEFg3IEMu5Zj.jpg",
    release_date: "2022-06-02",
    title: "Vikram",
    video: false,
    vote_average: 7.6,
    vote_count: 97,
  },
  {
    adult: false,
    backdrop_path: "/bOUKDbOe7hxGUHQHYJ7VCKkziZ3.jpg",
    genre_ids: [28, 53, 80, 12],
    id: 432139,
    original_language: "ta",
    original_title: "விக்ரம் வேதா",
    overview:
      "A notorious gangster Vedha surrenders himself to encounter specialist Vikram whom he challenges every step of the way by narrating his life events in the form of riddles that needs to be solved in order to capture him.",
    popularity: 8.421,
    poster_path: "/ob9YxdzRu5lfKgz0PNrlL45dorf.jpg",
    release_date: "2017-07-21",
    title: "Vikram Vedha",
    video: false,
    vote_average: 7.3,
    vote_count: 171,
  },
  {
    adult: false,
    backdrop_path: "/eXSJvPl4kOQFBaQqMSEOQJRaG1t.jpg",
    genre_ids: [53, 28],
    id: 540189,
    original_language: "te",
    original_title: "గూఢచారి",
    overview:
      "Gopi, is the son of an ex-RAW agent Raghuveer. Brought up by his uncle Sathya, he wants to be an agent just like his father and uncle. But Satya wants him to lead a normal life and not be killed like his father was. What happens in Gopi’s life that turns everything upside down?",
    popularity: 4.721,
    poster_path: "/uG04EjdV1zrj91ROxP75jwRxxv0.jpg",
    release_date: "2018-08-03",
    title: "Goodachari",
    video: false,
    vote_average: 6.7,
    vote_count: 38,
  },
];
